In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv('../Data/Raw/Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv')

In [34]:
df.head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0
2,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0

In [35]:
df['zip_code']=df['zip_code'].replace('Surburban', 'Suburban')

Fixed typo "Surburban" to "Suburban"

In [36]:
df.head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend
0,10,2) $100 - $200,142.44,1,0,Suburban,0,Phone,Womens E-Mail,0,0,0.0
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0
2,7,2) $100 - $200,180.65,0,1,Suburban,1,Web,Womens E-Mail,0,0,0.0
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0

In [37]:
df["Customer ID"] = ["C-" + str(i) for i in range(1, len(df) + 1)]

In [38]:
df

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,Customer ID
0,10,2) $100 - $200,142.44,1,0,Suburban,0,Phone,Womens E-Mail,0,0,0.0,C-1
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,C-2
2,7,2) $100 - $200,180.65,0,1,Suburban,1,Web,Womens E-Mail,0,0,0.0,C-3
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,C-4
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,C-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63995,10,2) $100 - $200,105.54,1,0,Urban,0,Web,Mens E-Mail,0,0,0.0,C-63996
63996,5,1) $0 - $100,38.91,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,C-63997
63997,6,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,C-63998
63998,1,5) $500 - $750,552.94,1,0,Suburban,1,Multichannel,Womens E-Mail,0,0,0.0,C-63999
63999,1,4) $350 - $500,472.82,0,1,Suburban,0,Web,Mens E-Mail,0,0,0.0,C-64000

Added Customer ID to make columns to identify uniquely

In [39]:
df.drop(columns='history_segment',inplace=True)

In [40]:
df

,recency,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,Customer ID
0,10,142.44,1,0,Suburban,0,Phone,Womens E-Mail,0,0,0.0,C-1
1,6,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,C-2
2,7,180.65,0,1,Suburban,1,Web,Womens E-Mail,0,0,0.0,C-3
3,9,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,C-4
4,2,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,C-5
...,...,...,...,...,...,...,...,...,...,...,...,...
63995,10,105.54,1,0,Urban,0,Web,Mens E-Mail,0,0,0.0,C-63996
63996,5,38.91,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,C-63997
63997,6,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,C-63998
63998,1,552.94,1,0,Suburban,1,Multichannel,Womens E-Mail,0,0,0.0,C-63999
63999,1,472.82,0,1,Suburban,0,Web,Mens E-Mail,0,0,0.0,C-64000

Dropping "history_segment" as they are bins of "history" and nothing different

In [41]:
df.to_csv('../Data/Processed/Hillstorm_prepocessed.csv',index=False)

Saved preprocessed data in Data/Processed/Hillstorm_prepocessed.csv

In [42]:
df["history_floor"] = (df["history"] == 29.99).astype(int)

In [43]:
df.head()

,recency,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,Customer ID,history_floor
0,10,142.44,1,0,Suburban,0,Phone,Womens E-Mail,0,0,0.0,C-1,0
1,6,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,C-2,0
2,7,180.65,0,1,Suburban,1,Web,Womens E-Mail,0,0,0.0,C-3,0
3,9,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,C-4,0
4,2,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,C-5,0

In [44]:
from sklearn.model_selection import train_test_split

strata = df["segment"] + "_" + df["conversion"].astype(str)

train, test = train_test_split(df, test_size=0.20, random_state=42, stratify=strata)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)

In [45]:
print(train.shape, test.shape)
print(train.groupby("segment")["conversion"].agg(["size", "sum", "mean"]))
print(test.groupby("segment")["conversion"].agg(["size", "sum", "mean"]))

(51200, 13) (12800, 13)
                size  sum      mean
segment
Mens E-Mail    17046  214  0.012554
No E-Mail      17045   98  0.005749
Womens E-Mail  17109  151  0.008826
               size  sum      mean
segment
Mens E-Mail    4261   53  0.012438
No E-Mail      4261   24  0.005632
Womens E-Mail  4278   38  0.008883

In [46]:
train.to_csv("../Data/Processed/train.csv", index=False)
test.to_csv("../Data/Processed/test.csv", index=False)

**Next Preprocessing steps:**
- Log transform of history
- Encoding categorical Cols